# Configuration file for Faster RCNN

####################
# Common params    #
####################
model_name: 'faster_rcnn_inception_resnet_v2_atrous_coco'
model_path: '/home/dat/model_zoo/faster_rcnn_inception_resnet_v2_atrous_coco'
label_map: './ml_service/object_detection/label_maps/mscoco.pbtxt'

#######################
# Inference Parameters#
#######################
inference:
  host:            localhost
  port:            9000
  frame_width:     640
  frame_height:    480
  score_threshold: 0.2


#########################
# Deployment Parameters #
#########################
deploy_params:
  output_path:      /home/dat/model_zoo   # it will generate a directory using `model_name`
  version:          1                     # a TF Serving may have multiple versions
  iou_threshold:    0.5
  score_threshold:  0.0

